#! /bin/bash

FILE=docker-compose.yml
ENV_FILE=.env

docker-compose -f ${FILE} --env-file=${ENV_FILE} down
docker-compose -f ${FILE} --env-file=${ENV_FILE} build
docker-compose -f ${FILE} --env-file=${ENV_FILE} up -d
docker-compose exec php composer install
