version: '3'
services:
  php:
    build:
      context: 'docker/php'
    volumes:
      - './:/var/www/html'
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/logs/ &&
             chmod -R 755 /var/www/html/logs/ &&
             exec php-fpm"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_LOCAL_NAME}
      MYSQL_USER: ${DB_LOCAL_USER}
      MYSQL_PASSWORD: ${DB_LOCAL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'
  memcached:
    image: memcached:latest
    ports:
      - "11212:11211"
